In [1]:
import sys, os
sys.path.append(os.path.abspath(".."))

In [ ]:
from src.morta_nuts2.data.raw_data import*
from src.morta_nuts2.data.raw import*

In [3]:
import geopandas as gpd

### Test fonctions imports de data eurostat

In [ ]:
shapef = gpd.read_file("C:/Users/Idrissa Belem/Documents/GitHub/test_projet/NUTS_files/NUTS_RG_01M_2024_3035.shp")

mxt_raw = load_mxt_raw(shapef,country="BE")
Dxt_raw = load_dxt_raw(shapef,country="BE")
Lxt_raw = load_lxt_raw(shapef,country="BE",download=True)

[Eurostat] Chargé depuis cache → ../data\BE_mxt_rawBE.csv  (771,936 lignes)
[Eurostat] Chargé depuis cache → ../data\BE_Dxt_raw_BE.csv  (115,566 lignes)
[Eurostat] Chargé depuis cache → ../data\BE_Lxt_rawBE.csv  (122,364 lignes)

In [5]:
mxt_raw = load_mxt_raw(shapef,country="FR",download=True)
Dxt_raw = load_dxt_raw(shapef,country="FR",download=True)
Lxt_raw = load_lxt_raw(shapef,country="FR",download=True)

[Eurostat] Téléchargé → ../data\FR_mxt_rawFR.csv  (1,543,872 lignes)
[Eurostat] Téléchargé → ../data\FR_Dxt_raw_FR.csv  (231,132 lignes)
[Eurostat] Téléchargé → ../data\FR_Lxt_rawFR.csv  (244,728 lignes)

In [5]:
mxt_raw

              values freq    indic_de sex  age   geo  time
0       6.700000e-04    A   DEATHRATE   T    0  BE10  1990
1       1.320000e-03    A   DEATHRATE   T    0  BE10  1991
2       8.200000e-04    A   DEATHRATE   T    0  BE10  1992
3       3.300000e-04    A   DEATHRATE   T    0  BE10  1993
4       4.900000e-04    A   DEATHRATE   T    0  BE10  1994
...              ...  ...         ...  ..  ...   ...   ...
771931  8.027293e+06    A  TOTPYLIVED   F   85  BE35  2019
771932  7.926502e+06    A  TOTPYLIVED   F   85  BE35  2020
771933  8.004917e+06    A  TOTPYLIVED   F   85  BE35  2021
771934  8.028586e+06    A  TOTPYLIVED   F   85  BE35  2022
771935  8.091807e+06    A  TOTPYLIVED   F   85  BE35  2023

[771936 rows x 7 columns]

In [6]:
Lxt_raw

         values freq unit sex  age   geo  time
0       12567.0    A   NR   T    0  BE10  1990
1       12799.0    A   NR   T    0  BE10  1991
2       12677.0    A   NR   T    0  BE10  1992
3       12808.0    A   NR   T    0  BE10  1993
4       12382.0    A   NR   T    0  BE10  1994
...         ...  ...  ...  ..  ...   ...   ...
118795     60.0    A   NR   F   99  BE35  2021
118796     71.0    A   NR   F   99  BE35  2022
118797     68.0    A   NR   F   99  BE35  2023
118798     65.0    A   NR   F   99  BE35  2024
118799     80.0    A   NR   F   99  BE35  2025

[118800 rows x 7 columns]

In [7]:
Dxt_raw

        values freq unit sex  age   geo  time
0         80.0    A   NR   T    0  BE10  1990
1        105.0    A   NR   T    0  BE10  1991
2         90.0    A   NR   T    0  BE10  1992
3         80.0    A   NR   T    0  BE10  1993
4         74.0    A   NR   T    0  BE10  1994
...        ...  ...  ...  ..  ...   ...   ...
112195    22.0    A   NR   F   99  BE35  2019
112196    26.0    A   NR   F   99  BE35  2020
112197    26.0    A   NR   F   99  BE35  2021
112198    33.0    A   NR   F   99  BE35  2022
112199    26.0    A   NR   F   99  BE35  2023

[112200 rows x 7 columns]

In [8]:
#df_agg = Dxt_raw.groupby(["geo", "sex", "time"])["values"].sum().reset_index()

### Test fonction renvoyant le nombre de décès, l'exposition et les taux de mortalité brutes par région

In [9]:
from data.processed import*
#

In [10]:
Lxt_raw

         values freq unit sex  age   geo  time
0       12567.0    A   NR   T    0  BE10  1990
1       12799.0    A   NR   T    0  BE10  1991
2       12677.0    A   NR   T    0  BE10  1992
3       12808.0    A   NR   T    0  BE10  1993
4       12382.0    A   NR   T    0  BE10  1994
...         ...  ...  ...  ..  ...   ...   ...
118795     60.0    A   NR   F   99  BE35  2021
118796     71.0    A   NR   F   99  BE35  2022
118797     68.0    A   NR   F   99  BE35  2023
118798     65.0    A   NR   F   99  BE35  2024
118799     80.0    A   NR   F   99  BE35  2025

[118800 rows x 7 columns]

In [11]:
test_table = mortality_by_region(mxt_raw,Lxt_raw,Dxt_raw,regions,gender="M",country="BE")